/**
 * Post-processing constants: IATA airport codes and pattern definitions
 */

// =============================================================================
// IATA Airport Code → City Mapping
// =============================================================================

export const IATA_TO_CITY: Record<string, string> = {
    // Major hubs
    'IST': 'Istanbul',
    'DPS': 'Bali',
    'ARN': 'Stockholm',
    'JFK': 'New York',
    'LAX': 'Los Angeles',
    'LHR': 'London',
    'CDG': 'Paris',
    'FRA': 'Frankfurt',
    'AMS': 'Amsterdam',
    'DXB': 'Dubai',
    'SIN': 'Singapore',
    'HKG': 'Hong Kong',
    'NRT': 'Tokyo',
    'SYD': 'Sydney',
    'MEL': 'Melbourne',
    'SFO': 'San Francisco',
    'ORD': 'Chicago',
    'MIA': 'Miami',
    'ATL': 'Atlanta',
    'BOS': 'Boston',
    'SEA': 'Seattle',
    'DEN': 'Denver',
    'LAS': 'Las Vegas',
    'MCO': 'Orlando',
    'IAH': 'Houston',
    'DFW': 'Dallas',
    'PHX': 'Phoenix',
    'CLT': 'Charlotte',
    'EWR': 'Newark',
    'MSP': 'Minneapolis',
    'DTW': 'Detroit',
    'PHL': 'Philadelphia',
    'BKK': 'Bangkok',
    'ICN': 'Seoul',
    'PEK': 'Beijing',
    'PVG': 'Shanghai',
    'BOM': 'Mumbai',
    'DEL': 'Delhi',
    'SZX': 'Shenzhen',
    'CAN': 'Guangzhou',
    'MAD': 'Madrid',
    'BCN': 'Barcelona',
    'FCO': 'Rome',
    'MXP': 'Milan',
    'VIE': 'Vienna',
    'ZRH': 'Zurich',
    'CPH': 'Copenhagen',
    'OSL': 'Oslo',
    'HEL': 'Helsinki',
    'WAW': 'Warsaw',
    'PRG': 'Prague',
    'BUD': 'Budapest',
    'ATH': 'Athens',
    'CAI': 'Cairo',
    'JNB': 'Johannesburg',
    'CPT': 'Cape Town',
    'GRU': 'Sao Paulo',
    'GIG': 'Rio de Janeiro',
    'MEX': 'Mexico City',
    'YYZ': 'Toronto',
    'YVR': 'Vancouver',
    'YUL': 'Montreal',
};
